# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [4]:
print("Dimensions (number of axis)", A.ndim)
print ("Shape", A.shape)
print ("Size", A.size)
print ("Data type", A.dtype)

Dimensions (number of axis) 2
Shape (3, 5)
Size 15
Data type int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
elementwisesub = B - C
print("Elementwise subtraction\n", elementwisesub)
print()
elementwisemult = B * C
print("Elementwise multiplication\n", elementwisemult)
print()
matrixmult = B @ C
print("Matrix Multiplication\n", matrixmult)

Elementwise subtraction
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
expmatrix = np.exp(B)
print("Exponentiated matrix\n", expmatrix)
print()
minval_matrix = np.min(B)
print("Minimum value for whole matrix\n", minval_matrix)
print()
minval_row = np.min(B, axis=1)
print("Minimum value for each row\n", minval_row)
print()
minval_col = np.min(B, axis=0)
print("Minimun value for each column\n", minval_col)
print()
indexmin_matrix = np.argmin(B)
print("Index value for minimum in whole matrix\n", indexmin_matrix)
print()
indexmin_row = np.argmin(B, axis=1)
print("Index of the minimum value in each row:", indexmin_row)
print()
sumall_elem = np.sum(B)
print("Sum all of the elements\n", sumall_elem)
print()
mean_col = np.mean(B, axis=0)
print("Mean for each column:", mean_col)
print()
medi_col = np.median(B, axis=0)
print("Median for Columns\n", medi_col)

Exponentiated matrix
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value for whole matrix
 1

Minimum value for each row
 [1 4 7]

Minimun value for each column
 [1 2 3]

Index value for minimum in whole matrix
 0

Index of the minimum value in each row: [0 0 0]

Sum all of the elements
 45

Mean for each column: [4. 5. 6.]

Median for Columns
 [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [9]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [11]:
# Numpy will assume i want all  the elements from the unspecfidied axes, 
# like in the above example, we've only asked for the for the first row
# but numpy returns all from row 1 since we have specified when it shoudl stop

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [12]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [14]:
#use the function np.nditer from numpy
for i in np.nditer(A):
     print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [15]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [16]:
#the code first makes an array with 30 elements, 1 through 30 become 0 through 29
#then a.reshape(()) turns the array into a 3D array with 3 axes
#B having 3 axes means the new array has 2 blocks with 3 rows each, each has 5 elements per row

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [17]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [18]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [19]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [73]:
def add_mult_matrices(mat1, mat2, operation):
    if not isinstance(mat1, np.ndarray) or not isinstance(mat2, np.ndarray):
        raise TypeError("Error, Both inpts must be of type numpy.ndarray")
    if operation not in ['add', 'multiply']:
        print("Error, Operation 'add' or 'mulitply' only")
    
    if operation == 'add':
        if mat1.shape != mat2.shape:
            raise ValueError("Error, both matrices must be the same size!")
        return mat1 + mat2

    if operation == 'multiply':
        if mat1.shape[1] != mat2.shape[0]:
            raise ValueError("Error, number of columns in first matrix must be equal to the number of rows in the second! .")
        return np.dot(mat1, mat2)
    
A = np.array([[2, 4,], [6, 8]])
B = np.array([[1, 3], [5, 7]])

print(add_mult_matrices(A, B, 'add'))
print()
print(add_mult_matrices(A, B, 'multiply'))    

[[ 3  7]
 [11 15]]

[[22 34]
 [46 74]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [40]:
x = np.array([4, 3])

print("10.1.1")
print("A) X's Dimentions:", x.shape)
print()
print("B) 5x=", 5*x)
print()
print("C) 3x=", 3*x)
print()
print("D) 5x+3x=", (5*x) + (3*x))
print()
print("E) 8x=", 8*x)
print()
print("F) 4x-x=", (4*x) - x)
print()
xtransp = x.reshape(2,1)
print("G) X transposed and new dimensions:", xtransp, xtransp.shape)
print()
print("H) Is x+xT defined? No because the shapes dont match")
print()
print("I) ||x||=", np.linalg.norm(x))
#not sure if i need to do it manually since there is a function for finding the norm, but:
print("I) Manual ||x||=", ((4**2)+(3**2))**0.5)



10.1.1
A) X's Dimentions: (2,)

B) 5x= [20 15]

C) 3x= [12  9]

D) 5x+3x= [32 24]

E) 8x= [32 24]

F) 4x-x= [12  9]

G) X transposed and new dimensions: [[4]
 [3]] (2, 1)

H) Is x+xT defined? No because the shapes dont match

I) ||x||= 5.0
I) Manual ||x||= 5.0


In [38]:
print("10.1.2")
v = np.array([3, 7, 0, 11]).reshape(4, 1)
print("A) Dimensions of v", v.shape)
print()
print("B) 2v =", 2*v)
print()
print("C) 5v+2v =", (5*v)+(2*v))
print()
print("D) 4v-2v =", (4*v)-(2*v))
print()
vtransp = v.reshape(1, 4)
print("E) V transposed and new dimensions:", vtransp, vtransp.shape)
print()
print("F) ||v||=", np.linalg.norm(v))
print("F) Manual ||v||=", ((3**2) + (7**2) + (0**2) + (11**2))**0.5)

10.1.2
A) Dimensions of v (4, 1)

B) 2v = [[ 6]
 [14]
 [ 0]
 [22]]

C) 5v+2v = [[21]
 [49]
 [ 0]
 [77]]

D) 4v-2v = [[ 6]
 [14]
 [ 0]
 [22]]

E) V transposed and new dimensions: [[ 3  7  0 11]] (1, 4)

F) ||v||= 13.379088160259652
F) ||v||= 13.379088160259652


In [50]:
print ("10.1.3")
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])
print("A) ||v1|| =", ((4**2)+(3**2)+(1**2)+(5**2))**0.5)
print(v1-v2)
print("B) ||v1-v2|| =", ((2**2)+(0**2)+(0**2)+(4**2))**0.5)

10.1.3
A) ||v1|| = 7.14142842854285
[2 0 0 4]
B) ||v1-v2|| = 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [81]:
print("10.2.1")
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

print("A) 2A =", 2 * A)
print()
print("B) B-2A =", B - 2*A)
print()
print("C) 3C-2E = It's not defined since the shapes don't match")
print()
print("D) 2D-3C =", 2*D - 3*C)
print()
print("E) Dt+2D =", D.T + 2*D)
print()
print("F) 2Ct - 2Dt =", (2 * C.T) - (2 * D.T))
print()
print("G) At - B = It's not defined since the shapes don't match")
print()
print("H) AC = It's not defined since the shapes don't match")
print()
print("I) CD = ", np.dot(C, D))
print()
print("J) CB = It's not defined since the shapes don't match")
print()
print("K) CI =", np.dot(C, I))
print()
print("L) ABt =", np.dot (A, B.T))

10.2.1
A) 2A = [[ 4  2 -2]
 [ 2 -2  2]]

B) B-2A = [[ 0 -4  3]
 [ 0 -2 -4]]

C) 3C-2E = It's not defined since the shapes don't match

D) 2D-3C = [[3 2]
 [2 3]]

E) Dt+2D = [[ 9 12]
 [12  9]]

F) 2Ct - 2Dt = [[-4 -4]
 [-4 -4]]

G) At - B = It's not defined since the shapes don't match

H) AC = It's not defined since the shapes don't match

I) CD =  [[11 10]
 [10 11]]

J) CB = It's not defined since the shapes don't match

K) CI = [[1 2]
 [2 1]]

L) ABt = [[5 2]
 [7 4]]


In [93]:
print("10.2.2")
A = np.array([[2, 3, 4], [5, 4, 1]])
print("AAt =", np.dot(A, A.T))
print()
print("10.2.3")
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])
print("AB =\n", np.dot(A, B))
print("AC =\n", np.dot(A, C))
print()
print("B =\n", B)
print("C =\n", C)
#We can see that the usual rules of arithmatic dont apply with scales here, where AB = AC,
#usually we would say then B=C, but we can see that B does not = C when it comes to multiplying matrices




10.2.2
AAt = [[29 26]
 [26 42]]

10.2.3
AB =
 [[ 4  7]
 [ 8 14]]
AC =
 [[ 4  7]
 [ 8 14]]

B =
 [[2 1]
 [1 3]]
C =
 [[4 3]
 [0 2]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [94]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [95]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [96]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
#because views in numpy don't make new copies of data, they give another way to get the data, to save memory
